version: "3"
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html

    db:
        platform: linux/x86_64
        image: mysql:8.0
        container_name: Database
        environment:
            - MYSQL_HOST= 127.0.0.1
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=challenge_backend
        volumes:
            - db:/var/lib/mysql
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: PhpMyAdmin
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80

volumes:
    db:
        driver: local
